apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bottomline" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bottomline" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "bottomline" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9090

